### PR TITLE
feat: Add support for async proxy connection.

### PR DESCRIPTION
**Pull request by langyo**
## PR Info

- Dependencies: #1881 

## Bug Fixes

- [x] Now the proxy connection trait can use `async` declarations.

## Breaking Changes

- The proxy connection would always deal the data under asynchronous mode.

## Changes

- [x] Add an example for Cloudflare worker that control D1 database by sea-orm. See [this demo](https://github.com/langyo/cloudflare_worker_rust_demo). ~~It may need to fix the [upper dependent from Cloudflare](https://github.com/cloudflare/workers-rs) that is not supported to get the SQL execute result, such as last insert id.~~

### CODE REVIEW

**Comment by langyo** [comment]
Based on the work of [`worker-rs` #591](https://github.com/cloudflare/workers-rs/pull/591), this PR can now be officially considered for merging. After the upstream branch is successfully merged, I'll take some time to further supplement the demo of how to connect to Cloudflare's D1 based on `sea-orm`.

**Comment by langyo** [comment]
cc @tyt2y3 @billy1624 
I'd be very grateful if you could take a look at it some time..

**Comment by langyo** [comment]
Sorry to bother you again. I found that the main branch has released version 1.0 and is almost about to release version 1.1, but this PR has not been reviewed yet. Please take a look at it if possible.
This patch will further strengthen the robustness of the proxy connection interface, making it easier to connect to environments such as [NodeJS WASM runtime](https://nodejs.org/en/learn/getting-started/nodejs-with-webassembly) or some serverless containers like [Cloudflare Worker](https://workers.cloudflare.com/).

@tyt2y3 @billy1624

**Comment by tyt2y3** [comment]
sorry for missing this. I see, so the interface changed. Ideally we should break it in 1.0 haha!
since this feature is behind a guard, I hope it will be okay to break it lol

**Review by tyt2y3 — APPROVED** [review]

**Pull request merged**
