### PR TITLE
fix: update setting search path in postgres

### PR DESCRIPTION
**Pull request by jdrouet**
## Bug Fixes

When doing `ops.set_schema_search_path("first_schema,public")`, the initial code only took into consideration the `first_schema` because of the quotes in `'{schema}'`. Removing the quotes fixes this.

### CODE REVIEW

**Review by billy1624 — APPROVED** [review]
Thanks!! @jdrouet for spotting this.

> Related discussions: https://dba.stackexchange.com/a/175116

I adding a test case to validate it's actually working as expected :)

**Comment by billy1624** [comment]
Hey @tyt2y3, ready for review!

**Comment by jdrouet** [comment]
👋 gentle bump

**Review by tyt2y3 — COMMENTED** [review]
Thank you

**Pull request merged**
