### PR TITLE
First metric and tracing implementation

### PR DESCRIPTION
**Pull request by nappa85**
As discussed on https://github.com/SeaQL/sea-orm/discussions/372, I've done a first, minimal, implementation for tracing and metric support.
I'm actually using this version on my environment and it seems to works like a charm, especially the metric part.
For the Tracing part, I've instrumented a minimal part of crate methods, and I've decided to instrument it as level trace because I think a library crate should not be "too loud".
Maybe we could control that behavior with a feature if you prefer

### CODE REVIEW

**Comment by tyt2y3** [comment]
Awesome! Thank you for the big contribution again.
Looks really good so far.

I think tracing has logger output support, so we might want to put that shim behind a 'use-log' feature flag.

**Comment by nappa85** [comment]
> I think tracing has log output support, so we might want to put that shim behind a 'use-log' feature flag.

What do you mean by "log output support"?
To output log messages you need a subscriber, if you look the crate is in dev-dependencies in place of env-logger to allow test logging to work as before

**Comment by tyt2y3** [comment]
> What do you mean by "log output support"?

I found it, I mean this https://docs.rs/tracing/0.1.29/tracing/index.html#log-compatibility
Seems like the user can enable that feature flag on their own, so we don't have to do anything for it )

**Review by tyt2y3 — APPROVED** [review]
Seem good to me. @billy1624 thoughts?

**Comment by tyt2y3** [comment]
We will release this in `0.5.0`

**Pull request merged**
