### PR TITLE
Add UpVPN to COMMUNITY startups

### PR DESCRIPTION
**Pull request by 64bit**
## PR Info

Add UpVPN to community startups. 
sea-orm is used for SQLite and Postgres databases. 

Thank you!

- Closes 

- Dependencies:
  - 

- Dependents:
  - 

## New Features

- [ ] 

## Bug Fixes

- [ ] 

## Breaking Changes

- [ ] 

## Changes

- [ ]

### CODE REVIEW

**Comment by tyt2y3** [comment]
Oh wow that's a very cool and useful project! I especially liked that it is open-source.

**Review by tyt2y3 — APPROVED** [review]

**Comment by 64bit** [comment]
Glad to hear you liked it! 😌 

I'm a happy user of SeaORM, really well designed library and good documentation! 👏🏽

**Comment by tyt2y3** [comment]
Actually, if you wish to, you can submit a [testimonial](https://www.sea-ql.org/community-survey).

We are in the process of redesigning our website and we will be sure to make space to feature it!

**Comment by 64bit** [comment]
Absolutely! I just sumbitted testimonial.

The form did not provide much insight into what is the ideal length of testimonial. I have provided one which is short. Depending on how you would like it for the website, I'm happy to provide longer testimonial too.

**Pull request merged**
