### PR TITLE
Remove generics on find_by_id

### PR DESCRIPTION
**Pull request by billy1624**

### CODE REVIEW

**Comment by tyt2y3** [comment]
I think we should not remove the panics, there is still a possibility for it to happen, though the cause would ONLY be a wrongly defined Entity.

**Comment by billy1624** [comment]
Panics that we can't get rid of lolll

**Comment by tyt2y3** [comment]
Oh, unless we have a derive macro to return the number of enum variants at compile time, then match it against the arity of the type def at compile time!
How does it sound?

**Comment by tyt2y3** [comment]
Not for this PR may be

**Pull request merged**
