### PR TITLE
Fix FromQueryResult when Result is redefined

### PR DESCRIPTION
**Pull request by tasn**
Macros should only ever use absolute import paths.
Shorthands can clash (as they have in my case).

### CODE REVIEW

**Comment by tasn** [comment]
Still not a complete fix (seems to still be failing for me) with the same reason:
```
error[E0107]: this type alias takes 1 generic argument but 2 generic arguments were supplied
   --> svix-server/src/v1/endpoints/endpoint.rs:144:10
    |
144 | #[derive(FromQueryResult)]
    |          ^^^^^^^^^^^^^^^
    |          |
    |          expected 1 generic argument
    |          help: remove this generic argument
    |
note: type alias defined here, with 1 generic parameter: `T`
   --> svix-server/src/error.rs:16:10
    |
16  | pub type Result<T> = std::result::Result<T, Error>;
    |          ^^^^^^ -
    = note: this error originates in the derive macro `FromQueryResult` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by billy1624** [comment]
Hey @tasn, thank you for fixing this. We should have fully quantify it, I have go through all procedural macros and fixed some more of it. Please check https://github.com/tasn/sea-orm/compare/patch-1...billy1624:pr/495 and cherrypick it :P

**Comment by billy1624** [comment]
We could merge and release this in 0.6.0
CC @tyt2y3

**Review by billy1624 — APPROVED** [review]
Thanks!! @tasn

**Review by tyt2y3 — APPROVED** [review]

**Pull request merged**
