### PR TITLE
Added support for using sea-orm with #[deny(missing_docs)]

### LINKED ISSUE #1472: DeriveActiveEnum is incompatible with deny(missing_docs) attribute
## Description

When using `sea-orm = 0.11`, compilation throws an error when using `DeriveActiveEnum` with `#![deny(missing_docs)]`.

## Steps to Reproduce

Given the following example:
```rust
//! Hello World
#![deny(missing_docs)]

use sea_orm::entity::prelude::*;

/// This is my documentation.
#[derive(DeriveActiveEnum, EnumIter)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum MyEnum {
    /// This values means something.
    SomeValue = 1,
}
```

### Expected Behavior

The code should compile.

### Actual Behavior

`cargo check` answers:

```
    Checking sea-orm-test v0.1.0 (/tmp/sea-orm-test)
error: missing documentation for a struct
 --> src/lib.rs:7:10
  |
7 | #[derive(DeriveActiveEnum, EnumIter)]
  |          ^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:2:9
  |
2 | #![deny(missing_docs)]
  |         ^^^^^^^^^^^^
  = note: this error originates in the derive macro `DeriveActiveEnum` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `sea-orm-test` due to previous error
```

### Reproduces How Often

Happens always.

## Versions

```
sea-orm-test v0.1.0 (/tmp/sea-orm-test)
└── sea-orm v0.11.0
    ├── sea-orm-macros v0.11.0 (proc-macro)
    ├── sea-query v0.28.3
    │   ├── sea-query-derive v0.3.0 (proc-macro)
    ├── sea-strum v0.23.0
    │   └── sea-strum_macros v0.23.0 (proc-macro)
```

### PR DESCRIPTION
**Pull request by emirror-de**
As discussed in #1472, this PR addresses the issue to allow `#[deny(missing_docs)]` in crates having `sea-orm` as dependency by adding `#[doc = " Generated by sea-orm-macros"]` to derived types/variants/fields in `sea-orm-macros`.

## PR Info

- Closes #1472 

## New Features

- [x] Enables crates using `sea-orm` to use `#[deny(missing_docs)]`.

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @emirror-de, thanks for contributing!! Is this ready? Please click "Ready for review" once it's.

A nitpick: I wonder why there is a space before the documentation? `#[doc = " Generated by sea-orm-macros"]` Is there any reason behind it?

**Comment by emirror-de** [comment]
Thanks for the review! I added it as draft to have a base for discussion and I was not sure if I missed something.

> A nitpick: I wonder why there is a space before the documentation? #[doc = " Generated by sea-orm-macros"] Is there any reason behind it?

It is just a matter of style:

`#[doc = " Generated by sea-orm-macros"]` expands to `/// Generated by sea-orm-macros` while

`#[doc = "generated by sea-orm-macros"]` expands to `///generated by sea-orm-macros`  in source code.

The latter has been proposed in the corresponding issue. I personally prefer the first one, but I am happy to align it with the way it fits best for `sea-orm`.

I was also thinking in moving `missing_docs` from `warn` to `deny` in `sea-orm` and maybe add it to all the other crates that are currently missing it? But I am not sure if that is out of scope here?

**Comment by tyt2y3** [comment]
> `#[doc = " Generated by sea-orm-macros"]` expands to `/// Generated by sea-orm-macros` while

Interesting observation. I agree.

**Comment by tyt2y3** [comment]
> I was also thinking in moving `missing_docs` from `warn` to `deny` in `sea-orm` and maybe add it to all the other crates that are currently missing it? But I am not sure if that is out of scope here?

May be we can enable this in one of our tests or examples, so as to prove the point. And we will be able to catch it in our CI moving forward. But not changing it in `sea-orm` itself.

**Comment by emirror-de** [comment]
> May be we can enable this in one of our tests or examples, so as to prove the point. And we will be able to catch it in our CI moving forward. But not changing it in sea-orm itself.

OK, so you suggest adding a project to the examples with:

`Cargo.toml`
```toml
[dependencies]
sea-orm = { path = "../../", features = ["default"] }
```

`lib.rs`
```rust
//! Denying missing docs test.
#![deny(missing_docs)]
```
If I understood you correctly?

**Comment by tyt2y3** [comment]
Yes. Or we can simply hijack the `basic` example. It has no other external dependency (no web framework etc), so I bet it will work.

**Review by billy1624 — APPROVED** [review]
Hey @emirror-de, thanks for the CI update! I find there are more to be done. Adding `#![deny(missing_docs)]` alone won't catch it. We need to make the entity module as public in order to properly test it.

I'm going to take on the task :)

**Pull request merged**
