### PR TITLE
Add Copy to the derived traits for active enums

### PR DESCRIPTION
**Pull request by e-rhodes**
## PR Info

- Closes [#618](https://github.com/SeaQL/sea-orm/issues/618)

## Adds

Added command line flag `--with-copy-enums` to `sea-orm-cli`. If provided, the automatically generated enums will derive the `Copy` trait. Otherwise, the behavior is unchanged.

## Breaking Changes

No changes to public API methods, CLI behavior is backwards compatible.

## Changes

Added `with_copy_enums` parameter in several places to get the behavior from the CLI to `sea_orm_codegen` (basically added the new flag anywhere the `with-serde` flag got passed).

### CODE REVIEW

**Comment by tyt2y3** [comment]
Although as for now there is no reason those enums can't be `Copy` , I wanted them to feel `heavyweight` so they are only `Clone` but not copy.

**Comment by tyt2y3** [comment]
I think the behaviour of adding `Copy` should be opt-in instead of a `default`

**Review by billy1624 — APPROVED** [review]
Hey @e-rhodes, sorry for the delay! Thanks for contributions!!

The opt-in `--with-copy-enums` flag look great!

@tyt2y3 has any comments on the naming?

**Comment by tyt2y3** [comment]
Thank you. We may turn that on as default in the future!

**Comment by billy1624** [comment]
> Thank you. We may turn that on as default in the future!

Hey @tyt2y3, I'll make `--with-copy-enums` enabled by default

**Pull request merged**
