### PR TITLE
[CLI] Fix generating Enum with variant starts with number

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/1172

## Bug Fixes

- [x] [CLI] generate entity: add prefix `_` to enum variant starts with number

### CODE REVIEW

**Comment by tyt2y3** [comment]
@Yuubari what's the error message?

**Comment by Yuubari** [comment]
The same as in the original #1172:
```
   Compiling entity v0.1.0 (mw-tools/entity)
error: proc-macro derive panicked
 --> entity\src\sea_orm_active_enums.rs:5:49
  |
5 | #[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
  |                                                 ^^^^^^^^^^^^^^^^
  |
  = help: message: `"3d"` is not a valid identifier

error: could not compile `entity` due to previous error
```
If I change ‘3D’ in
```
#[sea_orm(string_value = "3D")]
```
to anything else, it compiles fine.

**Comment by tyt2y3** [comment]
Ah sad we need a test case for the generated Entity as well.

**Comment by billy1624** [comment]
Oh no... we fixed one bug and another bug emerged. Now we need to fix `DeriveActiveEnum`.

We need test cases for generated entity. I think we can generate the entity and see if it compile.

**Comment by billy1624** [comment]
Hey @Yuubari, please check https://github.com/SeaQL/sea-orm/pull/1219.

I'll add the tests for generated entity later. That's another PR. We need to patch it first.

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-orm/releases/tag/0.10.4

**Pull request merged**
