### PR TITLE
[cli] generate entity programmatically

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/1046
- Closes https://github.com/SeaQL/sea-orm/issues/1047

## Adds

- [x] Refactor `sea-orm-cli` to allow generate entity programmatically. The new API with an entry point of `GenerateEntity::new(database_url)` follow by a bunch of set methods to customize the generation behaviour.

### CODE REVIEW

**Comment by EstebanBorai** [comment]
Awesome @billy1624! Thanks a lot! Will be checking closely later today.

**Comment by JonasCir** [comment]
Hey thank you so much for tackling this so fast! 

One thing that I came up with is that this code (i.e., `GenerateEntity`)  maybe could be better located in `sea-orm-codegen` and not the CLI. 

Because for me as a developer using it 
```rust
use sea_orm_codegen::GenerateEntity;

GenerateEntity::new(database_url)
                .execute()
                .await?;
```
reads a little bit cleaner/better than `use sea_orm_cli::GenerateEntity`.

But consider this bike-shedding, I'm completely happy with the solution!

**Comment by JonasCir** [comment]
On second thought, it is perfectly fine as we just start the CLI programmatically.

**Review by EstebanBorai — COMMENTED** [review]
Looking good so far @billy1624!

**Comment by JonasCir** [comment]
Hey just one quick note:
`run_migrate_command` takes the sub-command as input while this uses a build style pattern. I do not have a strong preference for either style, however, it might be a good idea to stick to the same pattern in the re-exported methods.

**Pull request closed without merging**
