### PR TITLE
EntityModel derive-macro

### PR DESCRIPTION
**Pull request by nappa85**

### CODE REVIEW

**Comment by tyt2y3** [comment]
This is brilliant! It's much shorter than I thought it needed to be.
Btw, would you mind moving the code from `lib.rs` to a new file under the `derives` module, like the other macros?

**Comment by nappa85** [comment]
> This is brilliant! It's much shorter than I thought it needed to be.
> Btw, would you mind moving the code from `lib.rs` to a new file under the `derives` module, like the other macros?

Yes, this is a mere copy-paste of my code, only with some renaming in the process, I was sure it would have to be split like the other macros, but yesterday I didn't had time to put on it

**Comment by tyt2y3** [comment]
Sure, no problem. I think we'd be pretty close after this PR!

**Comment by nappa85** [comment]
I've added support for indexed and unique attributed, I stopped on default_value because of the new method it relies on

**Comment by nappa85** [comment]
I've made an hypothesis on default_value and default_expr implementation, I'm not sure it's what you intended

**Comment by tyt2y3** [comment]
> I've made an hypothesis on default_value and default_expr implementation, I'm not sure it's what you intended

Yes they are, accurately.

Thank you very much for this. 

For the scope of this PR, the only thing I'd ask for is probably the optional impl of 'schema_name' besides 'table_name' in the EntityTrait.

**Comment by nappa85** [comment]
I've seen the conflicts, I can update the macro to auto-fill PrimaryKeyTrait::ValueType with primary key type(s)

**Pull request merged**
