### PR TITLE
Add docker create script for contributors to setup databases locally

### PR DESCRIPTION
**Pull request by billy1624**

### CODE REVIEW

**Comment by tyt2y3** [comment]
Actually, we can use docker-compose

**Review by tyt2y3 — CHANGES_REQUESTED** [review]
We can use docker-compose yaml

**Comment by billy1624** [comment]
What I intended to do here is just setting up all the databases at once. Then, develop can fire it up when they want to. Instead of running all at once.

image

**Comment by billy1624** [comment]
> We can use docker-compose yaml

But... yes, this would be the conventional way of doing so. See
- https://github.com/launchbadge/sqlx/blob/f2b3cc8dc3035279243f3a636379f7f20838488a/.github/workflows/sqlx.yml#L217
- https://github.com/launchbadge/sqlx/blob/master/tests/docker-compose.yml

**Pull request merged**
