### PR TITLE
(de)serialize custom JSON types - 2

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/676

### CODE REVIEW

**Comment by tyt2y3** [comment]
Kind of works, yeah

**Comment by tyt2y3** [comment]
Awesome. Actually it would be great if we can invite someone to try this

**Comment by tyt2y3** [comment]
Just a nitpick, perhaps `DeriveTryGetableFromJson` should be named `TryGetableFromJson` to be consistent with `FromQueryResult`

**Comment by Sytten** [comment]
I actually need this so I might give it a shot

**Pull request merged**
