### PR TITLE
Composite key cursor pagination

### PR DESCRIPTION
**Pull request by tyt2y3**
Fixes https://github.com/SeaQL/sea-orm/issues/1209

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Interesting! We should extend this logic to `Identity::Ternary` as well

**Comment by tyt2y3** [comment]
@jacob-pro this might be all it takes?

**Comment by tyt2y3** [comment]
Would appreciate some input

**Comment by billy1624** [comment]
Any thoughts? @jacob-pro @Sytten

**Review by billy1624 — COMMENTED** [review]
LGTM

**Comment by jacob-pro** [comment]
I don't fully understand how the code works (I'm new to this library) - but the generated SQL looks correct!.
Thank you for fixing this!

**Pull request merged**
