### PR TITLE
Chore: docs grammar fix

### PR DESCRIPTION
**Pull request by tusharxoxoxo**
## PR Info

- Closes 

- Dependencies:
  - 

- Dependents:
  - 

## Adds

- [ ] 

## Fixes

- [ ] 

## Breaking Changes

- [ ] 

## Changes

- [ ] 
- [x] Fixed few grammatical errors

### CODE REVIEW

**Comment by tusharxoxoxo** [comment]
anyone 
I am new to this
can someone guide how to it??

**Review by billy1624 — COMMENTED** [review]
Hey @tusharxoxoxo, welcome and thanks for the proofreading!!
You even proofread the CHANGELOG :D

**Comment by tusharxoxoxo** [comment]
I was unable to find a better way 
to kill my time other that this

**Comment by tusharxoxoxo** [comment]
Now, what should I do after u have assigned me this ??

**Review by billy1624 — APPROVED** [review]
Hey @tusharxoxoxo, the changes look good to me. Now let's wait @tyt2y3 to review and merge it. Thanks!!

**Review by tyt2y3 — APPROVED** [review]
Thank you so much for the chore

**Comment by tyt2y3** [comment]
I think Billy 'assigns' a PR to someone when it's not on his stack anymore.

**Pull request merged**
