### PR TITLE
Codegen add serde derives to enums, if specified

### LINKED ISSUE #461: SeaORM CLI not adding serde derives to Enums
I'm currently playing with `sea-orm` coming from `diesel-rs` and I love it! But I ran into this error while using enums and serde, the enums do not contain any serde derives.

### Reproduction

With a simple PostgreSQL schema

```sql
CREATE TYPE "user_kind_type" AS ENUM ('host', 'client');

CREATE TABLE users (
  "id" SERIAL PRIMARY KEY,
  "kind" "user_kind_type" NOT NULL
);
```

Running the following command (same behaviour with either `serialize`, `deserialize`, `both`):

```sh
sea-orm-cli generate entity -o src/entities --with-serde serialize
```

Creates the following file with Enums that does not contain the serde derives, where the errors propagates to the users model's `kind` column. 

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_kind_type")]
pub enum UserKindType {
    #[sea_orm(string_value = "client")]
    Client,
    #[sea_orm(string_value = "host")]
    Host,
}
```

### Expected Result

I would expect enums, just like models, to contain the derive. 

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_kind_type")]
pub enum UserKindType {
    #[sea_orm(string_value = "client")]
    Client,
    #[sea_orm(string_value = "host")]
    Host,
}
```

### PR DESCRIPTION
**Pull request by BenJeau**
### Related Issues
closes #461 

### Changes
- Added support for serde derives for enums (following the same method as `write_entities()`

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @BenJeau, thank you so much for the quick fix!

**Comment by BenJeau** [comment]
No problem! The source code is clean and I was easily able to write up a fix - my first PR in a Rust related repo :)

**Comment by billy1624** [comment]
Welcome to the Rust party! :P
Thanks for the support and we love to hear from the community

**Review by billy1624 — APPROVED** [review]
Ty!

**Pull request merged**
