### PR TITLE
refactoring Schema to expose functions for database updates

### PR DESCRIPTION
**Pull request by mohs8421**
This PR aims to expose functionality already available within a Schema to make it easier to update databases after changes.

## Changes

- Schema now has `get_column_def()` to make the creation of `TableAlterStatement` easier in migrations

### CODE REVIEW

**Comment by tyt2y3** [comment]
Good to have

**Comment by billy1624** [comment]
Hey @mohs8421, thanks for contributing!! Seems this PR is still in progress and there are more internal functions to be extracted and made public? Let me know when it's ready :)

**Comment by mohs8421** [comment]
> Hey @mohs8421, thanks for contributing!! Seems this PR is still in progress and there are more internal functions to be extracted and made public? Let me know when it's ready :)

yes, I want to extract the part about foreign keys as well, it should be almost straight forward too, although the confusion about `TableForeignKey` and `ForeignKeyCreateStatement` is a little bit anoying, since the later is missing a `From<>` implementation, I have to implement the creation of that one to get to the first one. Currently working on some other code, so it unfortunately has to wait a little bit.

**Review by billy1624 — COMMENTED** [review]
Hey @mohs8421, looks good! I've a small refactoring https://github.com/mohs8421/sea-orm/pull/1

**Review by billy1624 — COMMENTED** [review]
Opppps... sorry, I forgot to set the name of the target table
https://github.com/mohs8421/sea-orm/pull/2

**Review by tyt2y3 — COMMENTED** [review]
✅

**Pull request merged**
