### PR TITLE
PaginatorTrait for SelectorRaw  bug: Working example

### PR DESCRIPTION
**Pull request by npapapietro**
## PR Info

Added unit tests that capture this bug https://github.com/SeaQL/sea-orm/issues/663. 

The mock tests seem to ignore it so I moved into the integration tests. I'm only testing for postgres locally and run the test like

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thanks, it helps!

**Comment by ikrivosheev** [comment]
@tyt2y3 @npapapietro can I continue work on this PR in the internal branch? Or @npapapietro do you want to fix this?

**Comment by npapapietro** [comment]
@ikrivosheev I haven't had a chance to dig into this deeply so by all means I appreciate your help.

**Comment by ikrivosheev** [comment]
@npapapietro ok, I merge your PR into the internal branch and fix the bug)

**Comment by billy1624** [comment]
Hey @ikrivosheev, is this fixed?

**Comment by billy1624** [comment]
The issue was that we constructed the inner query separately from the outer query. Causing a reset in the parameter counter, you can observe there are two `$1`.

```rs
SELECT
  "inner_baker"."name"
FROM
  (
    SELECT
      "baker"."id",
      "baker"."name",
      "baker"."contact_details",
      "baker"."bakery_id"
    FROM
      "baker"
    WHERE
      "baker"."name" LIKE $1
  ) AS "inner_baker"
LIMIT
  $1 OFFSET $2
```

**Comment by ikrivosheev** [comment]
@billy1624 hello! I will start work on the PR today or tomorrow.

**Comment by billy1624** [comment]
> @billy1624 hello! I will start work on the PR today or tomorrow.

Take your time! :)

**Pull request merged**
