### PR TITLE
Generate entity files with PostgreSQL's schema name

### LINKED ISSUE #334: Schema name is missing in the generated Model entity (Postgresql)
I'm running `sea-orm-cli` code generator on Postgresql and using the schema name CLI option, but the 
schema_name attribute is missing in the generated table entity:

```
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "valid_schema_name", table_name = "valid_table_name")]
pub struct Model {
}
```

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Resolve #334

### CODE REVIEW

**Comment by tyt2y3** [comment]
under what condition will schema be generated? always? or only when it is not `public`?

**Comment by billy1624** [comment]
> under what condition will `schema` be generated? always? or only when it is not `public`?

Will always generate `schema_name` for PostgreSQL, even when it's `public`. And it won't generate `schema_name` for MySQL & SQLite.

**Comment by tyt2y3** [comment]
> Will always generate `schema_name` for PostgreSQL, even when it's `public`. And it won't generate `schema_name` for MySQL & SQLite.

I think a better behaviour is only generate `schema_name` when it is not `public`

**Comment by billy1624** [comment]
> > Will always generate `schema_name` for PostgreSQL, even when it's `public`. And it won't generate `schema_name` for MySQL & SQLite.
> 
> I think a better behaviour is only generate `schema_name` when it is not `public`

Updated. Check 7137aa25aa5293146ff22c6fcd7989d7fb6f2017

**Comment by tyt2y3** [comment]
Sorry for the conflict, I would actually want to merge it now

**Comment by itsbalamurali** [comment]
@billy1624 @tyt2y3 any plans to merge this sooner?

**Comment by tyt2y3** [comment]
Conflict. Sad :(

**Comment by billy1624** [comment]
Conflict once again resolved

**Comment by tyt2y3** [comment]
Finally

**Pull request merged**
