### PR TITLE
replaced usize with u64 in PaginatorTrait

### PR DESCRIPTION
**Pull request by liberwang1013**
## PR Info
this pr replaced ```usize``` with ```u64```  in paginated query. 

## Changes
- [x] relaced ```usize``` with ```u64``` in trait ```PaginatorTrait```
- [x] relaced ```usize``` with ```u64``` in struct ```Paginator```

### CODE REVIEW

**Review by ikrivosheev — APPROVED** [review]
@liberwang1013 thank you! LGTM!

**Comment by tyt2y3** [comment]
Thank you for the contribution. Was there an issue context that why you think u64 is a better choice than usize?

**Comment by liberwang1013** [comment]
> 



> Thank you for the contribution. Was there an issue/ context that why you think u64 is a better choice than usize?

actually the *Paginator* Wrapped https://docs.rs/sea-orm/0.8.0/sea_orm/entity/prelude/struct.Select.html, they have different input variable types. I hope this can be kept consistent with.

**Review by billy1624 — APPROVED** [review]
Thanks for the contributions! @liberwang1013

**Comment by billy1624** [comment]
> Thank you for the contribution. Was there an issue/ context that why you think u64 is a better choice than usize?

Hey @tyt2y3, the context: https://discord.com/channels/873880840487206962/900758376164757555/983627886756003891

**Comment by tyt2y3** [comment]
Let me think twice 🤔

**Comment by ikrivosheev** [comment]
@tyt2y3, I review PR: https://github.com/SeaQL/sea-orm/pull/768#discussion_r911351420 and here we use: `usize`.

**Comment by ikrivosheev** [comment]
@tyt2y3, @billy1624  prepared PR for the update sqlx, I think that changing the type is not such a terrible change.

**Review by billy1624 — APPROVED** [review]
I think the changes align SeaORM's pagination utility with SeaQuery statement. Because SeaQuery's [limit](https://docs.rs/sea-query/0.26.2/sea_query/query/struct.SelectStatement.html#method.limit) & [offset](https://docs.rs/sea-query/0.26.2/sea_query/query/struct.SelectStatement.html#method.offset) methods both take an `u64`.

Although it's a breaking change to SeaORM API - changing `usize` to `u64` - but it should be alright since it's a expansion in value range.

**Comment by tyt2y3** [comment]
Thanks guys

**Pull request merged**
