### PR TITLE
First implementation of config for generate entity

### LINKED ISSUE #1185: Config file of `sea-orm-cli generate entity` command
## Motivation

The options and flags for `sea-orm-cli generate entity` command is getting more and more. It's time to consider a scalable plan: loading the options from a config file.

## Proposed Solutions

Load all options by providing the path to the config file: `sea-orm-cli generate entity --config generate-entity.config.json`. The config file must be a JSON value.

```json
{
    "compact_format": true,
    "expanded_format": true,
    "include_hidden_tables": true,
    "tables": "my_table",
    "ignore_tables": ["seaql_migrations"],
    "max_connections": 1,
    "output_dir": "out",
    "database_schema": "public",
    "database_url": "postgres://root:root@localhost/database",
    "with_serde": "none",
    "with_copy_enums": true,
    "date_time_crate": "chrono",
    "lib": true
}
```

## Related Discussion

- https://github.com/SeaQL/sea-orm/issues/1120#issuecomment-1279875816

### PR DESCRIPTION
**Pull request by aadi58002**
## PR Info

- Closes #1185 

- Dependencies:
merge = "0.1.0"
serde = "1.0"
serde_json = "1.0.91"

## New Features

- [-]  Add config parsing option and flag to the cli generate entity command

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you for you contribution! I like the overall implementation, however, as stated, I think some options not related to code generation should be removed from the config file.
We should remove `database_url` and `max_connections`, as I don't think it's a good practice to checkin those, and I think they are already configurable with environment variables

**Comment by aadi58002** [comment]
> Thank you for you contribution! I like the overall implementation, however, as stated, I think some options not related to code generation should be removed from the config file. We should remove `database_url` and `max_connections`, as I don't think it's a good practice to checkin those, and I think they are already configurable with environment variables

Now. It will panic if those options are present in the config.

**Comment by aadi58002** [comment]
@tyt2y3

**Review by tyt2y3 — APPROVED** [review]
@billy1624 please make some adjustments as you see fit

**Comment by tyt2y3** [comment]
@billy1624 Do you want this to go into 0.11?

**Pull request closed without merging**
