### PR TITLE
Impl `TryGetableMany` for diffrent types of generices

### LINKED ISSUE #174: Impl `TryGetableMany` for diffrent types of generices `(A, B, C)`
Hi, I find that I cannot use the type `(i32, Uuid, i32)` as `PrimaryKeyTrait::ValueType`.

I think this is because `TryGetableMany` is only implemented for tuples with the same type (e.g. `(i32, i32, i32)`).

Solving this should be easy:
```rust
// change this:
impl<T> TryGetableMany for (T, T)
where
    T: TryGetable,
{
    fn try_get_many(res: &QueryResult, pre: &str, cols: &[String]) -> Result<Self, TryGetError> {
        try_get_many_with_slice_len_of(2, cols)?;
        Ok((
            T::try_get(res, pre, &cols[0])?,
            T::try_get(res, pre, &cols[1])?,
        ))
    }
}

// to this:
impl<T, U> TryGetableMany for (T, U)
where
    T: TryGetable,
    U: TryGetable,
{
    fn try_get_many(res: &QueryResult, pre: &str, cols: &[String]) -> Result<Self, TryGetError> {
        try_get_many_with_slice_len_of(2, cols)?;
        Ok((
            T::try_get(res, pre, &cols[0])?,
            U::try_get(res, pre, &cols[1])?,
        ))
    }
}
```

### PR DESCRIPTION
**Pull request by MuhannadAlrusayni**
Resolve #174
in addition I implemented `TryGetableMany` for 4 types tuple, and I think we will need more in the future.

### CODE REVIEW

**Comment by MuhannadAlrusayni** [comment]
wait don't merge this, looks like we need to do the same for `TryFromU64` to make #174 work.

**Comment by MuhannadAlrusayni** [comment]
Done. Waiting for reviews :D

**Comment by tyt2y3** [comment]
Thank you. Out of curiosity, why do you needed tuple of such high arity?

**Comment by MuhannadAlrusayni** [comment]
> Out of curiosity, why do you needed tuple of such high arity?

**Pull request merged**
