### PR TITLE
Add max_connections option to CLI

### PR DESCRIPTION
**Pull request by benluelo**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/511

## Adds

Adds a `--max-connections` flag to `sea-orm-cli`. Some databases have limits lower than the default 10 (elephantsql free tier, for example).

I was unable to get [pool_options](https://docs.rs/sea-orm/latest/sea_orm/struct.ConnectOptions.html#method.pool_options) to work (hence the standalone function), I enabled the `sqlx-dep` and it still wasn't showing up. If anyone could help me with this please let me know!

### CODE REVIEW

**Review by billy1624 — APPROVED** [review]
Hey @benluelo, sorry for the delay. Nicely done!

**Comment by billy1624** [comment]
> Actually, we don't have to make it an `Option`. I think it is a reasonable and better default for max connections to be `1`

Hey @benluelo, please cherrypick the useful bits :P
- https://github.com/benluelo/sea-orm/compare/feature/cli-max-connections...billy1624:pr/670

**Comment by benluelo** [comment]
Should be good to go now!

**Comment by tyt2y3** [comment]
Thank you

**Pull request merged**
