### PR TITLE
Delete all PostgreSQL types when calling fresh (#765)

### LINKED ISSUE #765: Migrate fresh not deleting postgres type
## Description

If the migration creates postgres types, running `sea-orm-cli migrate fresh` will fail because it doesn't delete types, and it will say that the type already exists.

## Steps to Reproduce

1. Create a migration which creates a postgres type.
2. Run the migration `sea-orm-cli migrate up`
3. Try to run a fresh migration `sea-orm-cli migrate fresh`

### Expected Behavior

The fresh migration should work

### Actual Behavior

The fresh migration returns an error saying that the enum type already exists.

### Reproduces How Often

always

## Versions

│   └── sea-orm v0.8.0
│       ├── sea-orm-macros v0.8.0 (proc-macro)
│       ├── sea-query v0.24.6
│       │   ├── sea-query-derive v0.2.0 (proc-macro)
│       │   ├── sea-query-driver v0.1.1 (proc-macro)
│       ├── sea-strum v0.23.0
│       │   └── sea-strum_macros v0.23.0 (proc-macro)
│   ├── sea-orm-migration v0.8.2
│   │   ├── sea-orm v0.8.0 (*)
│   │   ├── sea-orm-cli v0.8.1
│   │   │   ├── sea-schema v0.8.0
│   │   │   │   ├── sea-query v0.24.6 (*)
│   │   │   │   └── sea-schema-derive v0.1.0 (proc-macro)
│   │   ├── sea-schema v0.8.0 (*)
├── sea-orm v0.8.0 (*)
├── sea-orm-rocket v0.5.0
│   └── sea-orm-rocket-codegen v0.5.0 (proc-macro)

`uname -a`
Linux arch 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux

`pacman -Q postgresql`
postgresql 14.2-1

## Additional Information

Types should be first deleted when running a fresh migration.

### PR DESCRIPTION
**Pull request by karpa4o4**
## PR Info

Closes #765.

## Adds

This PR adds the removal of all PostgreSQL types in the current schema when calling fresh on migrator.

Unfortunately, it was not possible to remove all types without `for`, because when calling `names`, incorrect SQL is compiled.
```
DROP TYPE “test””test1”
```

### CODE REVIEW

**Review by billy1624 — APPROVED** [review]
Thanks!! @karpa4o4 LGTM!

**Review by billy1624 — COMMENTED** [review]
Btw... it'd be better if we have a migration test where we have PostgreSQL types (e.g. Enum) defined on the db. Can you create a new migration file where it define a new Enum on PostgreSQL?
- https://github.com/SeaQL/sea-orm/tree/master/sea-orm-migration/tests/migrator

**Comment by billy1624** [comment]
Hey @karpa4o4, I added a test for creating db enum on PostgreSQL
- https://github.com/karpa4o4/sea-orm/compare/issue/765...billy1624:pr/864

Feel free to cherrypick :D

**Comment by karpa4o4** [comment]
@billy1624, done

**Review by billy1624 — APPROVED** [review]
Thanks! @karpa4o4 You can fix the fmt warnings if you have time. This PR is good to merge, we can fix that after merged as well :)

**Comment by karpa4o4** [comment]
@billy1624, the fmt warnings fixed.

**Comment by billy1624** [comment]
Thank you so much @karpa4o4

**Review by billy1624 — APPROVED** [review]
Hey @karpa4o4, thanks again for contributing!! I'll merge this into a working branch and do a few refactoring before it get merged into master :)

**Pull request merged**
