### PR TITLE
Support Postgres network types (inet) #888

### PR DESCRIPTION
**Pull request by tusharxoxoxo**
## PR Info

https://github.com/SeaQL/sea-orm/issues/888
created a separate function for adding support for inet. I am not sure whether I have done it right or not. someone please point out mistakes and guide me to fix this.

- Closes 

- Dependencies:
  - 

- Dependents:
  - 

## New Features
added inet support using ipnet

## Bug Fixes

- [ ] 
- [ ] 

## Breaking Changes

- [ ] 

## Changes

- [ ]

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @tusharxoxoxo, thanks for contributing!!

I think we should support the follow three network types in SeaORM.
1. `ipnetwork::IpNetwork`
2. `std::net::IpAddr`
3. `mac_address::MacAddress`

We need to change the following places to support decoding those network types from (mock) query result.

1. Get the address types from `QueryResultRow::SqlxPostgres` to construct the model while leaving other `QueryResultRow` returns `Err` https://github.com/SeaQL/sea-orm/blob/92aa919f84e91235e2d272fdc8d1f66b62f6237a/src/executor/query.rs#L313-L401

2. Get the address types from `QueryResultRow::SqlxPostgres` to construct the JSON object https://github.com/SeaQL/sea-orm/blob/92aa919f84e91235e2d272fdc8d1f66b62f6237a/src/query/json.rs#L76-L135

**Comment by tusharxoxoxo** [comment]
I am on it. If I have any doubts/confusion then I will ask on discord. thanks billy

**Comment by yallxe** [comment]
Any updates on this? Maybe need some help?

**Comment by yallxe** [comment]
No needs to be sorry, it's okay ;) I'm here to help if needed, I kind of need that feature too.

**Pull request closed without merging**
