### PR TITLE
Suppress `ouroboros` missing docs warnings

### PR DESCRIPTION
**Pull request by billy1624**
## Info
- ~Depends on joshua-maros/ouroboros#49~

### CODE REVIEW

**Comment by tyt2y3** [comment]
Fun!

**Comment by tyt2y3** [comment]
There must be another way not relying on upstream.
It shows up in code review too often!

**Comment by billy1624** [comment]
> There must be another way not relying on an upstream PR. It shows up in code review too often!

Yep! See 8e7dc55

**Comment by tyt2y3** [comment]
Great yeah.

**Pull request merged**
