### PR TITLE
CLI allow generate entity with url without password

### LINKED ISSUE #435: sea-orm-cli passwordless database user causes "No password was found in the database url" error
when you try to generate an entity using the `sea-orm-cli generate entity --database-url "mysql://root@localhost/<dbname>"` command it panics with the error `thread 'main' panicked at 'No password was found in the database url'`

is there some other way to log into a database user without a password?

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Resolve #435

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @jokil123, could you try this PR?

You need to clone this repo. Then, install this updated `sea-orm-cli`. Run the following command in the repo root.

```sh
cargo install --path sea-orm-cli --force
```

Thanks!!

**Comment by jokil123** [comment]
Thanks a lot for this quick fix, it seems to have worked and solved the issue

**Comment by billy1624** [comment]
> Thanks a lot for this quick fix, it seems to have worked and solved the issue

Thanks for catching this issue :)

**Comment by tyt2y3** [comment]
Thanks! @billy1624

**Pull request merged**
