### PR TITLE
Codegen SQLite

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Depends on SeaQL/sea-schema#36

### CODE REVIEW

**Comment by billy1624** [comment]
You can run the codegen on any SQLite db by executing
```sh
// Inside `sea-orm/sea-orm-cli` directory
cargo run -- generate entity --database-url sqlite:///absolute/path/to/sakila.db --output-dir ../issues/386/src/out
```

**Comment by tyt2y3** [comment]
What are the files under issues/386 for?

**Comment by billy1624** [comment]
> What are the files under issues/386 for?

Just for demo

**Review by tyt2y3 — COMMENTED** [review]
I will remove the 386 folder

**Pull request merged**
