### PR TITLE
Add axum example

### PR DESCRIPTION
**Pull request by YoshieraHuang**
An `axum` version of `actix_example` is added into `examples` folder.

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you so much for the contribution! We will definitely give it a try and merge it.

**Review by billy1624 — APPROVED** [review]
Looks good to me! Tested locally on my machine with Postgres & Mysql

**Review by tyt2y3 — APPROVED** [review]
Thank you so much

**Comment by adityaa72** [comment]
@billy1624 I created an e-commerce website using sea-orm and postgres not completed yet but might help someone.
 [demo](https://github.com/jamsrworld/ecommerce-rust-nextjs-mcart)

**Pull request merged**
