### PR TITLE
Support schemas in queries

### LINKED ISSUE #65: Support schemas in queries
As far as I'm aware, there seems to be a lack of support for querying from schemas. For example, switching from public schema to a different schema.

A possible solution is that `EntityName` should support a new function called `schema_name` perhaps:
```rust
pub trait EntityName {
    fn schema_name(&self) -> Option<&str> {
        None
    }
}
```
Where `None` would not include a schema selector in the queries.. and `Some(&str)` would append the schema before the table name in queries.

This would change queries from:
```sql
SELECT "users"."id", "users"."email" FROM "users" ...
```
to:
```sql
SELECT "user"."users"."id", "user"."users"."email" FROM "user"."users" ...
-- or
SELECT "public"."users"."id", "public"."users"."email" FROM "public"."users" ...
```

### PR DESCRIPTION
**Pull request by billy1624**
Resolve #65

### CODE REVIEW

**Comment by billy1624** [comment]
Ok, let's leave the `RelationDef` for another PR?

**Comment by tyt2y3** [comment]
Yes agreed

**Comment by billy1624** [comment]
Feel like this part should be handled by `sea-query`, mapping from `TableRef` to table name `Iden`.

https://github.com/SeaQL/sea-orm/blob/3d9b7457f6ace3fd2b498ee6c45aef3ca3d8f2fd/src/query/helper.rs#L298-L306

**Comment by tyt2y3** [comment]
> Feel like this part should be handled by `sea-query`, mapping from `TableRef` to table name `Iden`.
> 
> https://github.com/SeaQL/sea-orm/blob/3d9b7457f6ace3fd2b498ee6c45aef3ca3d8f2fd/src/query/helper.rs#L298-L306

Did I wrote this code?

**Comment by billy1624** [comment]
@tyt2y3 check check

**Comment by billy1624** [comment]
> > Feel like this part should be handled by `sea-query`, mapping from `TableRef` to table name `Iden`.
> > https://github.com/SeaQL/sea-orm/blob/3d9b7457f6ace3fd2b498ee6c45aef3ca3d8f2fd/src/query/helper.rs#L298-L306
> 
> Did I wrote this code?

I wrote

**Comment by tyt2y3** [comment]
Okay, well I don't have a thought yet. Good enough for now if it works.

**Comment by billy1624** [comment]
> Okay, well I don't have a thought yet. Good enough for now if it works.

Hahaaa, okay!

**Pull request merged**
