### PR TITLE
Struct / enum derive PartialEq should also derive Eq

### PR DESCRIPTION
**Pull request by w93163red**
## PR Info

- Closes 
https://github.com/SeaQL/sea-orm/issues/965

## Adds

[codegen] Struct / enum derive PartialEq should also derive Eq

## Changes

Add a function to check if f32/f64 exists on the column. If not, add Eq on the derived part.

Testing:
1. update the previous tests to match the new mechanism. 
2. Add two tests to if Eq is not generated when f32/f64 in the column.

### CODE REVIEW

**Review by billy1624 — CHANGES_REQUESTED** [review]
Hey @w93163red, thanks for contributing!! Please check https://github.com/w93163red/sea-orm/pull/1 for the refactoring and fixes :D

**Comment by w93163red** [comment]
I merged the change~ Thanks!

**Review by billy1624 — APPROVED** [review]
Thanks again for contributing!! @w93163red

**Comment by tyt2y3** [comment]
Awesome

**Comment by frederikhors** [comment]
It would be very useful to have this as soon as possible.

Every time we generate with 0.9.3 we have to undo the changes (I cannot disable linting in CI).

Can we release 0.9.4 with this only?

**Comment by tyt2y3** [comment]
Can

**Comment by frederikhors** [comment]
> Can do

? Are you going to?

**Pull request merged**
