### PR TITLE
Customize column names

### LINKED ISSUE #43: Support non snake-case column name
We assume all columns in database table are in snack-case.

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
}
```

We need to support an optional derive attribute to override this assumption.

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
#[DeriveColumn(case = "camel")]
pub enum Column {
    Id,
    Name,
}
```

Or, customize column name of each variants

```rust
#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    #[DeriveColumn(name = "ID")]
    Id,
    Name,
}
```

### PR DESCRIPTION
**Pull request by billy1624**
Resolve #43

### CODE REVIEW

**Comment by Acidic9** [comment]
> I insist that after we released a new version of sea-orm-macro, we bump the dependency and remove the `path =` from toml to ensure that our CI uses the released version.

I noticed that it used path also, wasn't sure if it was a mistake or not.

This is awesome, you guys work so fast. Is there any examples of how to use this feature to rename columns?

**Comment by tyt2y3** [comment]
https://github.com/SeaQL/sea-orm/blob/8b30ef74a22153ebdb2e0cf65afd411fe68ba8a6/src/tests_cfg/filling.rs#L19-L34

**Comment by billy1624** [comment]
We want to keep it simple and avoid using excessive macros loll

**Comment by tyt2y3** [comment]
Though, I think we can instead use override:
```rust
 impl IdenStatic for Column { 
     // the default impl is self.as_str()
     fn rename(&self) -> &str { 
         match self { 
             Self::Id => "id", 
             _ => self.as_str(), 
         } 
     } 
 } 
```

**Comment by Acidic9** [comment]
Ohh okay I see 😄 Serde uses a macro for renaming, but I guess the `default_as_str()` approach works fine too.. just a little bit more boiletplate code

**Comment by Acidic9** [comment]
Does the renaming also need to be implemented for `DeriveModel`? I'm not sure how to handle a model with fields which need to be renamed.

**Comment by billy1624** [comment]
Our assumption on naming model attributes & column enum variants:
- All model attributes are in snake-case and exists in column enum variants
  - Model attributes: `id`, `name`
- All column variants are in camel-case and exists in model attributes
  - Enum variants: `Id`, `Name`

So, that means if you want to rename one of the column / attribute you have to also update the other half of it.

**Comment by Acidic9** [comment]
I'm still a little confused, for the column you would rename it with `DeriveCustomColumn` and `impl IdenStatic for Column`.. but how do we rename a field on the model too? For exampe, if a field conflicts with a Rust keyword.

**Comment by billy1624** [comment]
So basically the `impl IdenStatic for Column` is just for constructing SQL statement, i.e. how we refer this column in SQL statement.

Take your example in #76... we might do the followings

```rust
#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: i32,
    pub type_of: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveCustomColumn)]
pub enum Column {
    Id,
    TypeOf,
}

impl IdenStatic for Column {
    fn as_str(&self) -> &str {
        match self {
            Self::TypeOf => "type",
            _ => self.default_as_str(),
        }
    }
}
```

**Comment by Acidic9** [comment]
Ah perfect, it all makes sense now thank you @billy1624 ... again XD !!!

**Pull request merged**
