### PR TITLE
change: rename `core` crate to `service` in examples

### PR DESCRIPTION
**Pull request by df51d**
## PR Info
This pull request addresses the issue of naming conflicts with the 'core' crate in the project's examples. Currently, the 'core' crate causes issues when used in conjunction with certain macros that rely on the '::core::result::Result' or any item from the Rust '::core' namespace. This PR proposes renaming the 'core' crate to 'service' throughout the examples to resolve these conflicts and improve usability. 

## Changes
- Renamed the 'core' crate to 'service' in all example files.
- Updated references to the renamed crate in the documentation and code comments.

## Related Issue
- https://github.com/illicitonion/num_enum/issues/27

## Testing Done
I have tested only Axum example, but the rest should be working just fine.

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you for pointing this out. I am okay with changing them.

**Comment by df51d** [comment]
Just letting know in case you didn't see @tyt2y3 My latest commit fixed this so you can approve merge or re-run CI.

**Comment by billy1624** [comment]
Thanks!! @df51d I copy the script you provide up here for record. What a brilliant regex!

```
old="core" new="service" rg='(e-|_|"|^|\/)'"$old"; \
rg -le "$rg" --pcre2 ./ | \
  xargs -d '\n' \
    sed -i -E 's/'"$rg"'/\1'"$new"'/gm';\
find ./ -type d -name "$old" | \
  xargs -I {} sh -c \
    'git mv {} $(dirname {})/'"$new";\
rg "$old" -l issues examples/**/*.md | \
  xargs -d '\n' \
    sed -i "s/$old/$new/gm"
```

Originally posted at Discord https://discord.com/channels/873880840487206962/1108598496799502396/1108918609859838063

**Review by billy1624 — COMMENTED** [review]
Hey @df51d, thanks for the PR!! There are a lot of line changes. Let me check it carefully.

**Review by billy1624 — APPROVED** [review]
Thanks!! @df51d

**Pull request merged**
