### PR TITLE
add oura-postgres-sink to COMMUNITY.md

### PR DESCRIPTION
**Pull request by rvcas**
relates to #403 

closes https://github.com/dcSpark/oura-postgres-sink/issues/1

### CODE REVIEW

**Review by billy1624 — APPROVED** [review]
Thanks!! @rvcas

**Comment by tyt2y3** [comment]
Appreciated a lot. Actually this is a very interest project!

**Comment by billy1624** [comment]
Making on chain data searchable? Cool!

**Comment by rvcas** [comment]
@billy1624 yes

**Pull request merged**
