### PR TITLE
Rename column name & column enum variant

### LINKED ISSUE #194: Column name `type`
Hey,

when generating code column named `type` should be renamed to `r#type`. Maybe check other rust keywords.

### PR DESCRIPTION
**Pull request by billy1624**
Resolve #194

### CODE REVIEW

**Comment by tyt2y3** [comment]
We need some unit tests

Ref: https://github.com/SeaQL/sea-orm/blob/master/src/entity/column.rs#L412

**Review by tyt2y3 — CHANGES_REQUESTED** [review]
)))

**Comment by billy1624** [comment]
Unit tests added 088bfd0

**Review by tyt2y3 — APPROVED** [review]
Nice!

**Pull request merged**
