### PR TITLE
Cont. feat: expose database connection to `ActiveModelBehaviour`'s methods

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/962
- Continue https://github.com/SeaQL/sea-orm/pull/1145

## New Features

- [x] `before_save`, `after_save`, `before_delete` and `after_delete` methods of `ActiveModelBehavior` receive db connection as the parameter

## Breaking Changes

- [x] The `ActiveModelBehaviour` trait becomes async trait
  - For anyone who implement the `ActiveModelBehaviour` with default implementation (no-op). No code changes is required.
    ```rs
    impl ActiveModelBehavior for ActiveModel {}
    ```
  - If you overridden the default implementation:
    ```rs
    #[async_trait::async_trait]
    impl ActiveModelBehavior for ActiveModel {
        async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
        where
            C: ConnectionTrait,
        {
            // ...
        }

        // ...
    }
    ```

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @tyt2y3, we can include this on the upcoming release

**Review by tyt2y3 — CHANGES_REQUESTED** [review]
We need to have a test entity and some test cases for this

**Comment by billy1624** [comment]
Tests added

**Review by tyt2y3 — APPROVED** [review]
Interesting

**Comment by tyt2y3** [comment]
I feel like we will have a lot of documentation to write

**Comment by billy1624** [comment]
> I feel like we will have a lot of documentation to write

Yes, lots of breaking changes to be documented not to mention the new features lolll

**Pull request merged**
