### PR TITLE
Transaction support

### PR DESCRIPTION
**Pull request by nappa85**
As discussed on https://github.com/SeaQL/sea-orm/issues/142,
I've implemented transactions adding a DbConnection trait.

As always, I'm open to discussion, this time more that before since I've touched a lot of core things around

### CODE REVIEW

**Comment by nappa85** [comment]
It has been a long hard way out of hell, but I think I finished this PR

**Comment by tyt2y3** [comment]
Thank you so much for the hard work! I am trying to go through the extensive change.

Several questions popping in my head:

1) How'd it be like to actually perform a transaction?
2) Why is the `Mutex` needed?
3) Why is the `&*conn` needed in Rocket example?

**Comment by nappa85** [comment]
>     1. How'd it be like to actually perform a transaction?
It should work like sqlx::Connection::transaction, I'll write a test ASAP
>     2. Why is the `Mutex` needed?
The Mutex is needed because `sqlx::Executor` is implemented only for `&mut sqlx::Connection`
>     3. Why is the `&*conn` needed in Rocket example?
Didn't understood deeply myself that one, `Connection` impl `Deref<DatabaseConnection>` but it seems that the compiler isn't able to match that with the generic.
Haven't thought about that too much to be honest

**Comment by nappa85** [comment]
Had to move to `Pin<Box<dyn Future>>` to get out of a lifetime hell...

**Comment by tyt2y3** [comment]
Thank you so much for the expedition! I think, lifetime + async is probably 'fighting two Ferris' at once.

The only things left to discuss, is probably the namings )

I am thinking of renaming `DbConnection` to `ConnectionTrait` or `DatabaseFunctions`.

@billy1624 several followups we should do after merging:
1. remove the `is_mock_connection` checks and still make the test suite pass
2. investigate how to remove the extra `*` from Rocket example `save(&*conn)`
3. enhance our `MockConnection` such that it also 'supports' transaction

**Comment by nappa85** [comment]
> I am thinking of renaming `DbConnection` to `ConnectionTrait` or `DatabaseFunctions`.
Ok, I'll rename to ConnectionTrait ASAP

>     1. remove the `is_mock_connection` checks and still make the test suite pass
If you look at my commits, I've tried, but you'll end-up having the query built conditionally on sqlx-postgres feature, so you'll end up chasing the format, that it isn't what you want to do on a test

**Comment by tyt2y3** [comment]
> If you look at my commits, I've tried, but you'll end-up having the query built conditionally on sqlx-postgres feature, so you'll end up chasing the format, that it isn't what you want to do on a test

I get what you mean. So to clarify the intention, I think `Mock` should behave like Postgres if and only if the `backend` is Postgres, regardless of whether the `sqlx-postgres` feature exists. That means, yes, we should not remove the `is_mock_connection` check, but instead make it independent of the `sqlx-postgres` feature.

**Comment by nappa85** [comment]
> I get what you mean. So to clarify the intention, I think `Mock` should behave like Postgres if and only if the `backend` is Postgres, regardless of whether the `sqlx-postgres` feature exists. That means, yes, we should not remove the `is_mock_connection` check, but instead make it independent of the `sqlx-postgres` feature.

Well, if the query is built "postgres-style" independently from sqlx-postgres feature, the `is_mock_connection` method isn't needed anymore

**Comment by nappa85** [comment]
Sorry, it's monday morning...
I should have done a different branch for the last commit, it's a fix on the proc-macro we made, the Decimal column type was instantiated without the Option-al argument

**Comment by tyt2y3** [comment]
Oh, by the way, you should add `n***85@the***ing.com` to your GitHub account (https://github.com/settings/emails), that way you'd be properly credited!

**Comment by billy1624** [comment]
I think the `MockConnetion` can provide an API like...

```rust
async fn to_json_2() -> Result<(), DbErr> {
    let db = MockDatabase::new(DbBackend::Postgres)
        .append_query_results(vec![vec![maplit::btreemap! {
            "id" => Into::<Value>::into(128), "name" => Into::<Value>::into("apple")
        }]])
        .into_connection();

    db.transaction::<_, (), DbErr>(|db| Box::pin(async move {
        assert_eq!(
            cake::Entity::find().into_json().one(db).await.unwrap(),
            Some(serde_json::json!({
                "id": 128,
                "name": "apple"
            }))
        );

        Ok(())
    })).await.unwrap();

    // With empty transaction log if rollback
    assert_eq!(
        db.into_transaction_log(),
        vec![
            Transaction::from_sql_and_values(
                DbBackend::Postgres,
                r#"INSERT INTO "cake" ("cake"."id", "cake"."name") VALUES ($1, $2)"#,
                vec![128u64.into(), "apple".into()]
            ),
        ]
    );

    Ok(())
}
```

**Comment by nappa85** [comment]
> That's fine.
> Oh, by the way, you should add your commit email `n***85@the***ing.com` to your GitHub account (https://github.com/settings/emails) (or commit using your account's primary email), that way you'd be properly credited!
> Last time I actually rewrote the commit author (https://github.com/SeaQL/sea-orm/commits?author=nappa85)

You're right, that happens because I'm working from my office laptop...

**Pull request merged**
