### PR TITLE
Implemented support for `FromQueryResult` to work with generics 

### PR DESCRIPTION
**Pull request by leviska**
## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/1463

## New Features

- [x] Support for `FromQueryResult` to work with generics

### CODE REVIEW

**Comment by leviska** [comment]
I couldn't find tests for macros, so added them in a new file, let me know if there is a better way

**Comment by leviska** [comment]
It seems that failed check is not because of this pr

**Comment by tyt2y3** [comment]
Yes, I think master has been fixed now.

**Comment by tyt2y3** [comment]
Thank you for the contribution! It looks good at first glance, but I would like to take a closer look later.

**Comment by leviska** [comment]
Hey, any updates?

**Review by billy1624 — APPROVED** [review]
Hey @leviska, thanks for contributing!! LGTM :P

**Review by tyt2y3 — APPROVED** [review]
Nice work! Thank you.
It seems like we can include this in a patch release too.

**Pull request merged**
