### PR TITLE
Adding config option for flag in sea-orm-cli generate entity

### LINKED ISSUE #1185: Config file of `sea-orm-cli generate entity` command
## Motivation

The options and flags for `sea-orm-cli generate entity` command is getting more and more. It's time to consider a scalable plan: loading the options from a config file.

## Proposed Solutions

Load all options by providing the path to the config file: `sea-orm-cli generate entity --config generate-entity.config.json`. The config file must be a JSON value.

```json
{
    "compact_format": true,
    "expanded_format": true,
    "include_hidden_tables": true,
    "tables": "my_table",
    "ignore_tables": ["seaql_migrations"],
    "max_connections": 1,
    "output_dir": "out",
    "database_schema": "public",
    "database_url": "postgres://root:root@localhost/database",
    "with_serde": "none",
    "with_copy_enums": true,
    "date_time_crate": "chrono",
    "lib": true
}
```

## Related Discussion

- https://github.com/SeaQL/sea-orm/issues/1120#issuecomment-1279875816

### PR DESCRIPTION
**Pull request by aadi58002**
## PR Info

- Closes  #1185 

## New Features

- [x] Adds a option to have a config file for the generate entity sea-orm-cli command.

### CODE REVIEW

**Comment by aadi58002** [comment]
@tyt2y3 or @billy1624 
can you review the PR and give feedback for changes?

**Review by billy1624 — COMMENTED** [review]
Hey @aadi58002, thanks for the initiative and for contributing!!

I agree that we should split the fields in `GenerateSubcommands::Entity( ... )` into a separate struct (`GenerateSubCommandsEntity`) as you just did.

However, can we keep the field type in `GenerateSubCommandsEntity` untouched? I imagine the user will always provide the `database_url` and `database_schema`. The config file (if provided) will override all other options and flags. i.e. `sea-orm-cli entity generate -url mysql://sea:sea@localhost/bakery -schema bakery -config my_config.json`

**Comment by aadi58002** [comment]
> Hey @aadi58002, thanks for the initiative and for contributing!!
> 
> I agree that we should split the fields in `GenerateSubcommands::Entity( ... )` into a separate struct (`GenerateSubCommandsEntity`) as you just did.
> 
> However, can we keep the field type in `GenerateSubCommandsEntity` untouched? I imagine the user will always provide the `database_url` and `database_schema`. The config file (if provided) will override all other options and flags. i.e. `sea-orm-cli entity generate -url mysql://sea:sea@localhost/bakery -schema bakery -config my_config.json`

We can skip the url and schema field during de serialized i think which does make it so that database_url and database_scheme will not be de serialized from the config and will need to be provided from the cli

**Comment by aadi58002** [comment]
@billy1624  can you review this PR?

**Comment by aadi58002** [comment]
@billy1624 or @tyt2y3 Can you review this PR and give feedback?

**Pull request closed without merging**
