### PR TITLE
Exposing connection pools for sqlite

### PR DESCRIPTION
**Pull request by ys928**
## Changes

- Provide a function to expose sqlite connection pools

### CODE REVIEW

**Comment by tyt2y3** [comment]
I think this might be what you're looking for? https://github.com/SeaQL/sea-orm/blob/010433bf1633dd387f8493071c0b3838a7fbb575/src/database/db_connection.rs#L537

**Comment by ys928** [comment]
thanks, I didn't find it beforehand, turns out I also needed to add a sea-orm-internal feature to show this function in vscode's autocompletion

**Comment by tyt2y3** [comment]
I think I will expose it by default moving forward

**Comment by ys928** [comment]
That's great, but I think this function should be included in the sqlx-sqlite feature.After all, it might not make sense to be able to use it without enabling this feature.

**Comment by tyt2y3** [comment]
Yes, the method itself is guarded by `sqlx-sqlite`

**Comment by ys928** [comment]
Oh, indeed, I was wrong, everything is fine.

**Pull request closed without merging**
