### PR TITLE
Transaction Support

### PR DESCRIPTION
**Pull request by tyt2y3**
#142 continue

### CODE REVIEW

**Comment by tyt2y3** [comment]
Let's get movin @billy1624

**Comment by nicoulaj** [comment]
Maybe you could include `ConnectionTrait` in the prelude ? Btw, `QuerySelect` and `QueryOrder`are also missing (`QueryFilter`, `QueryResult` are included so it feels a bit inconsistent).

**Comment by tyt2y3** [comment]
@nappa85 well, I tried to rebase the branch onto master, which is quite daunting indeed. Let me know if anything is missing.

**Comment by nappa85** [comment]
Seems ok to me, it's quite difficult to spot a difference on this ocean of
changes, but the key points seems to be there

Il giorno sab 18 set 2021 alle ore 17:01 Chris Tsang <
***@***.***> ha scritto:

**Pull request merged**
