### PR TITLE
Codegen Handle Self Referencing & Multiple Relations to the Same Related Entity

### LINKED ISSUE #239: [sea-orm-cli] Better handling of relation generations
It has been reported that the codegen can generate non-compilable code when dealing with relations.

As the first step, we can simply skip generating the relations if:

1) the related entity is self::Entity (https://github.com/SeaQL/sea-orm/discussions/231#discussioncomment-1449066)
2) there exist multiple relations to the same related Entity (#218)

Later, we can also try to generate Links inplace of those relations.

### PR DESCRIPTION
**Pull request by billy1624**
## PR Info
- Resolve #239

### CODE REVIEW

**Comment by AngelOnFira** [comment]
I took a quick read through the code, but not a deep dive yet. I'll try doing some exports on my databases when I get time, and see what comes up. Super excited to see this!

**Comment by billy1624** [comment]
> I took a quick read through the code, but not a deep dive yet. I'll try doing some exports on my databases when I get time, and see what comes up. Super excited to see this!

Do let us know the test results :P
Thanks!!

**Review by tyt2y3 — APPROVED** [review]
TBH, I did not author `codegen`. Way more complicated than I thought. Seems cool enough though.

**Comment by AngelOnFira** [comment]
Alright, I loaded in my database, and it seems to `cargo check` properly. I will have to play with the ergonomics of using it, but this is very promising! Thanks for the work :smiley:

Here is a model with two fields that reference a wallet (some code was removed):

```rust
//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "currencies_transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub amount: Option<i32>,
    pub from_wallet_id: Option<i64>,
    pub to_wallet_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::currencies_wallet::Entity",
        from = "Column::FromWalletId",
        to = "super::currencies_wallet::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CurrenciesWallet2,
    #[sea_orm(
        belongs_to = "super::currencies_wallet::Entity",
        from = "Column::ToWalletId",
        to = "super::currencies_wallet::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CurrenciesWallet1,
}

impl Related<super::currencies_trade_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrenciesTradeTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
```

**Comment by billy1624** [comment]
Nice!!

**Pull request merged**
