### PR TITLE
Support `Vec<u8>` primary key

### LINKED ISSUE #286: Support for BYTEA Postgres primary keys
Currently any column marked as a primary key needs to satisfy `TryFromU64`.

A BYTEA (`Vec<u8>`) does not satisfy this (and, I don't think ever could).

Would it be possible to add support for this type of primary key?  We use it a lot in our application

### PR DESCRIPTION
**Pull request by billy1624**
- Resolve #286

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @tyt2y3, I was wondering why `ColumnType::Binary` is defined as without length in sea-orm?

Because of that, I can't seems to get around [this](https://github.com/SeaQL/sea-orm/runs/4077110887?check_suite_focus=true#step:6:189).

```
Error: Exec("error returned from database: 1170 (42000): BLOB/TEXT column 'id' used in key specification without a key length")
```

**Comment by tyt2y3** [comment]
The `BYTEA` type in Postgres does not have a length.

**Comment by tyt2y3** [comment]
@robot-head can you share your schema definition? I bet the index should have a key length

**Comment by billy1624** [comment]
> Hey @tyt2y3, I was wondering why `ColumnType::Binary` is defined as without length in sea-orm?
> 
> Because of that, I can't seems to get around [this](https://github.com/SeaQL/sea-orm/runs/4077110887?check_suite_focus=true#step:6:189).
> 
> ```
> Error: Exec("error returned from database: 1170 (42000): BLOB/TEXT column 'id' used in key specification without a key length")
> ```

Btw... this only failed on MySQL & MariaDB. Postgres is working perfectly

**Comment by tyt2y3** [comment]
Well, can we default `1024` it inside SeaORM?

**Comment by billy1624** [comment]
> Well, can we default `1024` it inside SeaORM?

For MySQL & MariaDB only and leave Postgres untouched?

**Comment by tyt2y3** [comment]
Edited.

**Comment by billy1624** [comment]
> Okay, then we should use `sea_query::ColumnType::Binary(Some(1024))` explicitly for the test case.

That would work but how about ordinary user that want to use [`create_table_from_entity`](https://docs.rs/sea-orm/0.3.1/sea_orm/schema/struct.Schema.html#method.create_table_from_entity) on MySQL & MariaDB? They will fall into this trap as well if they happen to use `Vec<u8>` (`blob` db type) as primary key.

**Comment by tyt2y3** [comment]
Looks good. Anything missing? I am about to make a minor release.

**Comment by billy1624** [comment]
Go for it

**Pull request merged**
