### PR TITLE
Unchanged ActiveValue as Set

### PR DESCRIPTION
**Pull request by billy1624**
## New Features

- [x] Converting `Unchanged` active value as `Set`

### CODE REVIEW

**Comment by tyt2y3** [comment]
Umm I think there might be more self-explanatory method names

**Comment by billy1624** [comment]
Agree! Let me brainstorm it tonight in dream.
Any other naming suggestions are welcomed!

**Comment by billy1624** [comment]
How about `unchanged_value_into_set`?

**Comment by billy1624** [comment]
Okay, renamed

**Comment by tyt2y3** [comment]
I think we should instead only add two methods to `ActiveModel`: `iter` and `iter_mut`.
And then the user can do:

```rust
active_model.iter_mut(|(_col, &mut val)| {
    *val = match val {
        ActiveValue::Unchanged(v) => ActiveValue::Set(v),
        _ => (),
    };
});
```

**Comment by billy1624** [comment]
Let user perform the conversion on their own?

**Comment by billy1624** [comment]
We just provide a API to effortlessly iterate all fields in the ActiveModel.

And we should include a code snippet in the cookbook on how to update all `Unchanged` fields into `Set`

**Comment by tyt2y3** [comment]
May we could have a `rechange` method on ActiveValue:

```rust
active_model.iter_mut(|(_col, &mut val)| {
    *val = val.rechange();
});
```

**Comment by tyt2y3** [comment]
May be we don't have to bound the `V`

**Comment by tyt2y3** [comment]
Ah I see what you mean, sad :(

**Comment by billy1624** [comment]
Back the the naming problem. How about `set_dirty`?

**Comment by billy1624** [comment]
Any opinion on the naming? @tyt2y3

**Comment by tyt2y3** [comment]
Back to square 1, can we have `reset` and `reset_all`?

**Comment by billy1624** [comment]
Renamed :D

**Review by tyt2y3 — APPROVED** [review]

**Pull request merged**
